# Generated by Django 4.1.3 on 2022-11-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='default-pp.png', null=True, upload_to='media/images'),
        ),
    ]
