# Generated by Django 4.1.3 on 2022-11-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
    ]
