# Generated by Django 4.1.3 on 2022-11-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_address_user_gender_user_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
